# 《滚木派对》全局属性

# libGDX 版本
gdxVersion=1.13.5

# Android
androidPluginVersion=8.11.1
androidCompileSdk=36
androidMinSdk=26
androidTargetSdk=36
androidBuildTools=36.0.0

# Gradle 自身
org.gradle.jvmargs=-Xmx2560m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=false
